# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx10G
org.gradle.daemon=false
org.gradle.parallel=true
dev.kikugie.stonecutter.hard_mode=true

# Tools
stonecutter_version = 0.10-alpha.8
grgit_version = 5.2.1

# Mod Properties
mod_version 			= 1.6.2
maven_group 			= dev.tr7zw
archives_base_name 		= entityculling
modid                   = entityculling
author                  = tr7zw